# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: NativeScript Developer Day 2017
email: brian.rinaldi@progress.com
event_dates: September 18-19, 2017
event_city: New York City
event_tagline: JavaScript. Mobile. Native.
description: > # this means to ignore newlines until "baseurl:"
  The official NativeScript community event returns. Learn to build
  mobile apps with JavaScript using the open source framework.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://developerday.nativescript.org" # the base hostname & protocol for your site
twitter_username: nativescript
github_username:  nativescript

# Build settings
markdown: kramdown
